### PR TITLE
Fix container builds, merge/rename spack-stack extension repos, add Intel oneAPI 2024.0.2 compiler/MPI on AWS ParallelCluster

### LINKED ISSUE #960: CI container build (using clang compiler) broken after last week's geos-gcm-env updates (pflogger error)
**Describe the bug**

See https://github.com/JCSDA/spack-stack/actions/runs/7608125753/job/20716678048

image

**To Reproduce**
See above

**Expected behavior**
No build errors

**System:**
Ubuntu 20 Docker container using `clang@10.0.0`

**Additional context**
n/a

### LINKED ISSUE #965: Container builds broken after moving spack extensions out of spack
**Describe the bug**
Following yesterday's merge that moves the spack extensions out of the spack submodule, we are having a problem with the container builds: https://github.com/JCSDA/spack-stack/actions/runs/7637196138/job/20805589102
```
#15 [builder 4/6] RUN cd /opt/spack-environment && spack env activate . && spack install --fail-fast && spack gc -y
#15 3.161 ==> Error: Package 'spack.pkg.builtin.base-env' not found.
#15 3.161 Use 'spack create' to create a new package.
#15 3.161 
#15 3.161 Did you mean one of the following packages?
#15 3.161   seq-gen
#15 3.161   aspell6-en
#15 3.161   r-base64enc
#15 ERROR: process "docker-shell cd /opt/spack-environment && spack env activate . && spack install --fail-fast && spack gc -y" did not complete successfully: exit code: 1
```

The problem is the way the spack container builds work: they clone spack (and spack alone) in the container for the install. Only the config is copied into the container from the machine that runs the build (i.e. runs docker).

@AlexanderRichert-NOAA Any ideas on how to fix this? Otherwise I fear we need to revert.

**To Reproduce**
See above

**Expected behavior**
Containers build

**System:**
Any building containers with spack

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by climbfuji**
### Summary

Several changes to fix the broken container builds and reorganize our repos:
- Update spack submodule pointer to include `pflogger` updates (to fix broken clang/mpich container builds of pflogger)
- Merge spack-stack extension repos in `spack-ext/repos`: combine `jcsda-emc` and `jcsda-emc-bundles` into `spack-stack` (we also have EPIC and may have more partners in the future, so this makes a lot of sense)
- Add logic to copy the spack-stack extension repos into the container: this requires recording the spack-stack hash as part of running `setup.sh` (so that docker can recognize updates and doesn't use the cache if spack-stack has changed) and physically copying the repos directory into the container environment directory (because the docker build runs from that directory and everything above is not in its context)

Unrelated, and commented out by default:
- Addition of Intel oneAPI compiler/MPI for `aws-pcluster` site for testing

### Testing

- [x] CI container builds **this can only be run after the spack PR is merged and the submodule ptr is updated in this PR**
    - [x] jedi-clang-mpich: https://github.com/JCSDA/spack-stack/actions/runs/7663766335/job/20887072436
    - [x] jedi-gcc-openmpi: https://github.com/JCSDA/spack-stack/actions/runs/7668917120/job/20901724670
    - [ ] ~~jedi-intel-impi~~ - will be run later
- [x] General CI builds
- [x] CI build on AWS R&D ParallelCluster: https://github.com/JCSDA/spack-stack/actions/runs/7663464277/job/20886322600

### Applications affected

n/a

### Systems affected

spack-stack containers

### Dependencies

- [x]  waiting on https://github.com/JCSDA/spack/pull/397

### Issue(s) addressed

Resolves https://github.com/JCSDA/spack-stack/issues/965
Resolves https://github.com/JCSDA/spack-stack/issues/960

### Checklist
- [x] This PR addresses one issue/problem/enhancement, or has a very good reason for not doing so.
- [ ] These changes have been tested on the affected systems and applications.
- [x] All dependency PRs/issues have been resolved and this PR can be merged.

### CODE REVIEW

File: setup.sh [hunk 1]
```diff
@@ -1,15 +1,3 @@
-# Use '-i' when sourcing this file to attempt to reset $PATH to system defaults (i.e., based on /etc/profile),
```
Comment (climbfuji) [inline setup.sh:1]: We haven't used this and I don't think we need it?

Comment (AlexanderRichert-NOAA) [reply setup.sh:1]: I guess I can go either way. I'm okay with removing it for now, but if we run into issues again like we had with the ESMF recipe where it was using the calling environment (incl. PATH) rather than the Spack build environment in places, then we should revisit and try to make it work on all systems (I don't remember how far I got with testing, I think it worked on more than just Acorn and Orion but those were the ones that needed added customization).

**Review by AlexanderRichert-NOAA — APPROVED** [review]
Looks good (apart from .gitmodules)

**Review by mathomp4 — APPROVED** [review]

File: setup.sh (hunk 1 above)
Comment (climbfuji) [reply setup.sh:1]: Ok, thanks. I'll take it out for now. I never had to do anything particular about the environment except for Cray systems where you need to have a separate set of modules loaded, depending on the compiler you build for (see Narwhal instructions). Since we've agreed today to move forward with separate environments for different compilers, that will be even less of an issue (again, essentially doing what we already do for Narwhal).
